language: php
os:
- linux
script: echo "do nothing."
before_deploy:
  - zip -r latest *
  - test -d dpl_cd_upload || mkdir dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
deploy:
  - provider: s3
    access_key_id: $aws_access_key
    secret_access_key:
      secure: $aws_secure_key
    local_dir: dpl_cd_upload
    skip_cleanup: true
    region: ap-northeast-1
    on:
      branch: master
    bucket: "${user}-web-codedeploy"
  - provider: codedeploy
    access_key_id: $aws_access_key
    secret_access_key:
      secure: $aws_secure_key
    bucket: "${user}-web-codedeploy"
    key: latest.zip
    application: ${user}-codedeploy-app
    deployment_group: In-place
    region: ap-northeast-1
    on:
      branch: master